import { and, eq } from "drizzle-orm";
import { assignments, assignmentEvents, assets, siteAuditLogs } from "@/src/db/site-schema";
import { withSiteDb } from "@/src/db/site-manager";
import { resolveSiteConnection } from "@/src/db/site-resolver";
import { AppError } from "@/src/lib/errors";

type CreateInput={siteId:string;assetId:string;profileId:string;assignedAt?:Date;notes?:string};
export async function createAssignment(input:CreateInput,actorId:string){const url=await resolveSiteConnection(input.siteId);try{return await withSiteDb(input.siteId,url,db=>db.transaction(async tx=>{const [asset]=await tx.select({id:assets.id,status:assets.status}).from(assets).where(and(eq(assets.id,input.assetId),eq(assets.siteId,input.siteId))).limit(1);if(!asset)throw new AppError("NOT_FOUND","Varlık bulunamadı.",404);if(["RETIRED","LOST","ARCHIVED"].includes(asset.status))throw new AppError("CONFLICT","Bu durumdaki varlık zimmetlenemez.",409);const [assignment]=await tx.insert(assignments).values({assetId:input.assetId,profileId:input.profileId,assignedByUserId:actorId,assignedAt:input.assignedAt,notes:input.notes}).returning();if(!assignment)throw new Error("Zimmet oluşturulamadı.");await tx.update(assets).set({status:"IN_USE",updatedAt:new Date()}).where(eq(assets.id,input.assetId));await tx.insert(assignmentEvents).values({assignmentId:assignment.id,action:"ASSIGNED",actorId,details:{profileId:input.profileId}});await tx.insert(siteAuditLogs).values({actorId,action:"ASSIGNMENT_CREATED",entityType:"ASSIGNMENT",entityId:assignment.id,metadata:{assetId:input.assetId,profileId:input.profileId}});return assignment}))}catch(error){if(isUniqueViolation(error))throw new AppError("CONFLICT","Varlığın zaten aktif bir zimmeti var.",409);throw error}}
export async function returnAssignment(id:string,input:{siteId:string;receivedByUserId?:string;returnedAt?:Date;notes?:string},actorId:string){const url=await resolveSiteConnection(input.siteId);return withSiteDb(input.siteId,url,db=>db.transaction(async tx=>{const [current]=await tx.select().from(assignments).where(and(eq(assignments.id,id),eq(assignments.status,"ACTIVE"))).limit(1);if(!current)throw new AppError("NOT_FOUND","Aktif zimmet bulunamadı.",404);const returnedAt=input.returnedAt??new Date();const [updated]=await tx.update(assignments).set({status:"RETURNED",returnedAt,receivedByUserId:input.receivedByUserId??actorId,notes:input.notes??current.notes}).where(eq(assignments.id,id)).returning();await tx.update(assets).set({status:"IN_STOCK",updatedAt:new Date()}).where(eq(assets.id,current.assetId));await tx.insert(assignmentEvents).values({assignmentId:id,action:"RETURNED",actorId,details:{returnedAt:returnedAt.toISOString()}});await tx.insert(siteAuditLogs).values({actorId,action:"ASSIGNMENT_RETURNED",entityType:"ASSIGNMENT",entityId:id,metadata:{assetId:current.assetId}});return updated}))}
function isUniqueViolation(error:unknown):boolean{return typeof error==="object"&&error!==null&&"code" in error&&error.code==="23505"}
