import { and, eq } from "drizzle-orm";
import { assets, mobileDetails, phoneUsers, siteAuditLogs } from "@/src/db/site-schema";
import { withSiteDb } from "@/src/db/site-manager";
import { resolveSiteConnection } from "@/src/db/site-resolver";
import { AppError } from "@/src/lib/errors";

type CreateInput={siteId:string;assetId:string;profileId?:string;sharedRoomId?:string;extension?:string;phoneNumber?:string;startDate:string;notes?:string;isPrimary:boolean};
export async function assignPhoneUser(input:CreateInput,actorId:string){const url=await resolveSiteConnection(input.siteId);try{return await withSiteDb(input.siteId,url,db=>db.transaction(async tx=>{const [asset]=await tx.select({id:assets.id}).from(assets).where(and(eq(assets.id,input.assetId),eq(assets.siteId,input.siteId))).limit(1);if(!asset)throw new AppError("NOT_FOUND","Telefon varlığı bulunamadı.",404);const [record]=await tx.insert(phoneUsers).values({assetId:input.assetId,profileId:input.profileId,sharedRoomId:input.sharedRoomId,extension:input.extension,phoneNumber:input.phoneNumber,startDate:input.startDate,notes:input.notes,isPrimary:input.isPrimary,assignedByUserId:actorId,isActive:true}).returning();if(!record)throw new Error("Telefon kullanıcısı oluşturulamadı.");await tx.update(mobileDetails).set({userChangedAt:new Date()}).where(eq(mobileDetails.assetId,input.assetId));await tx.insert(siteAuditLogs).values({actorId,action:"PHONE_USER_ASSIGNED",entityType:"PHONE_USER",entityId:record.id,metadata:{assetId:input.assetId,profileId:input.profileId,sharedRoomId:input.sharedRoomId}});return record}))}catch(error){if(isUniqueViolation(error))throw new AppError("CONFLICT","Telefonun zaten aktif bir ana kullanıcısı var.",409);throw error}}
export async function closePhoneUser(id:string,input:{siteId:string;endDate?:string;notes?:string},actorId:string){const url=await resolveSiteConnection(input.siteId);return withSiteDb(input.siteId,url,db=>db.transaction(async tx=>{const [current]=await tx.select().from(phoneUsers).where(and(eq(phoneUsers.id,id),eq(phoneUsers.isActive,true))).limit(1);if(!current)throw new AppError("NOT_FOUND","Aktif telefon kullanıcısı bulunamadı.",404);const [closed]=await tx.update(phoneUsers).set({isActive:false,endDate:input.endDate??new Date().toISOString().slice(0,10),notes:input.notes??current.notes}).where(eq(phoneUsers.id,id)).returning();await tx.update(mobileDetails).set({userChangedAt:new Date()}).where(eq(mobileDetails.assetId,current.assetId));await tx.insert(siteAuditLogs).values({actorId,action:"PHONE_USER_CLOSED",entityType:"PHONE_USER",entityId:id,metadata:{assetId:current.assetId}});return closed}))}
function isUniqueViolation(error:unknown):boolean{return typeof error==="object"&&error!==null&&"code" in error&&error.code==="23505"}
