import { and, eq, or } from "drizzle-orm";
import { currentUser } from "@/src/auth/session";
import { authorizeSite, requireWriteRole } from "@/src/auth/access";
import { controlDb } from "@/src/db/control";
import { adProfiles, assetCategories, provinces, racks, sites } from "@/src/db/control-schema";
import { assetMovements, assetRelations, assets, computerDetails, mobileDetails, networkDetails, printerDetails, siteAuditLogs } from "@/src/db/site-schema";
import { resolveSiteConnection } from "@/src/db/site-resolver";
import { withSiteDb } from "@/src/db/site-manager";
import { reserveAssetCode } from "@/src/services/asset-code";
import { updateAssetSchema } from "@/src/validation/assets";
import { AppError, errorResponse, ok } from "@/src/lib/errors";

export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){try{const user=await currentUser();const siteId=new URL(request.url).searchParams.get("siteId");if(!siteId)throw new AppError("VALIDATION_ERROR","siteId zorunludur.",400);await authorizeSite(user,siteId);const id=(await params).id;const url=await resolveSiteConnection(siteId);const result=await withSiteDb(siteId,url,async db=>{const [asset]=await db.select().from(assets).where(and(eq(assets.id,id),eq(assets.siteId,siteId))).limit(1);if(!asset)throw new AppError("NOT_FOUND","Varlık bulunamadı.",404);const [computer,mobile,printer,network,relations,movements]=await Promise.all([db.select().from(computerDetails).where(eq(computerDetails.assetId,id)).limit(1),db.select().from(mobileDetails).where(eq(mobileDetails.assetId,id)).limit(1),db.select().from(printerDetails).where(eq(printerDetails.assetId,id)).limit(1),db.select().from(networkDetails).where(eq(networkDetails.assetId,id)).limit(1),db.select().from(assetRelations).where(or(eq(assetRelations.sourceAssetId,id),eq(assetRelations.targetAssetId,id))),db.select().from(assetMovements).where(eq(assetMovements.assetId,id))]);return {asset,details:computer[0]??mobile[0]??printer[0]??network[0]??null,relations,movements}});if(result.details&&"rackId" in result.details){const network=result.details;const [rack,profile]=await Promise.all([network.rackId?controlDb.select({name:racks.name,shortCode:racks.shortCode}).from(racks).where(eq(racks.id,network.rackId)).limit(1):Promise.resolve([]),network.responsibleProfileId?controlDb.select({displayName:adProfiles.displayName}).from(adProfiles).where(eq(adProfiles.id,network.responsibleProfileId)).limit(1):Promise.resolve([])]);return ok({...result,details:{...network,rackName:rack[0]?`${rack[0].name} · ${rack[0].shortCode}`:null,responsibleProfileName:profile[0]?.displayName??null}})}return ok(result)}catch(error){return errorResponse(error)}}

export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){try{const user=await currentUser();requireWriteRole(user);const parsed=updateAssetSchema.safeParse(await request.json());if(!parsed.success)throw new AppError("VALIDATION_ERROR","Varlık bilgileri geçersiz.",400,parsed.error.flatten());const input=parsed.data;await authorizeSite(user,input.siteId);const id=(await params).id;const url=await resolveSiteConnection(input.siteId);let newCode:string|undefined;let oldCode:string|undefined;if(input.details?.kind==="network"&&input.details.rackId){const nextRackId=input.details.rackId;const current=await withSiteDb(input.siteId,url,db=>db.select({rackId:networkDetails.rackId,assetCode:assets.assetCode,categoryId:assets.categoryId,provinceId:assets.provinceId}).from(assets).innerJoin(networkDetails,eq(networkDetails.assetId,assets.id)).where(and(eq(assets.id,id),eq(assets.siteId,input.siteId))).limit(1));const record=current[0];if(record&&record.rackId!==nextRackId){const [context]=await controlDb.select({provinceCode:provinces.code,siteCode:sites.code,rackCode:racks.shortCode,categoryCode:assetCategories.code}).from(sites).innerJoin(provinces,eq(provinces.id,sites.provinceId)).innerJoin(racks,and(eq(racks.siteId,sites.id),eq(racks.id,nextRackId))).innerJoin(assetCategories,eq(assetCategories.id,record.categoryId)).where(eq(sites.id,input.siteId)).limit(1);if(!context?.categoryCode)throw new AppError("VALIDATION_ERROR","Yeni kabin veya kategori kodu geçersiz.",400);oldCode=record.assetCode;newCode=await withSiteDb(input.siteId,url,db=>reserveAssetCode(db,{siteId:input.siteId,rackId:nextRackId,categoryId:record.categoryId},{provinceCode:context.provinceCode,siteCode:context.siteCode,rackCode:context.rackCode,categoryCode:context.categoryCode!}))}}
  const updated=await withSiteDb(input.siteId,url,db=>db.transaction(async tx=>{const [current]=await tx.select().from(assets).where(and(eq(assets.id,id),eq(assets.siteId,input.siteId))).limit(1);if(!current)throw new AppError("NOT_FOUND","Varlık bulunamadı.",404);const {details,...common}=input;const archivedAt=common.status===undefined?current.archivedAt:common.status==="ARCHIVED"?new Date():null;const [asset]=await tx.update(assets).set({...common,assetCode:newCode??current.assetCode,updatedAt:new Date(),archivedAt}).where(eq(assets.id,id)).returning();if(details?.kind==="computer")await tx.insert(computerDetails).values({assetId:id,hostname:details.hostname,operatingSystem:details.operatingSystem}).onConflictDoUpdate({target:computerDetails.assetId,set:{hostname:details.hostname,operatingSystem:details.operatingSystem}});if(details?.kind==="mobile")await tx.insert(mobileDetails).values({assetId:id,imei1:details.imei1,imei2:details.imei2,phoneNumber:details.phoneNumber,lineNumber:details.lineNumber,operatingSystem:details.operatingSystem}).onConflictDoUpdate({target:mobileDetails.assetId,set:{imei1:details.imei1,imei2:details.imei2,phoneNumber:details.phoneNumber,lineNumber:details.lineNumber,operatingSystem:details.operatingSystem}});if(details?.kind==="printer")await tx.insert(printerDetails).values({assetId:id,ipAddress:details.ipAddress,macAddress:details.macAddress,printerName:details.printerName,connectionType:details.connectionType,isNetworkPrinter:details.isNetworkPrinter,roomId:common.roomId}).onConflictDoUpdate({target:printerDetails.assetId,set:{ipAddress:details.ipAddress,macAddress:details.macAddress,printerName:details.printerName,connectionType:details.connectionType,isNetworkPrinter:details.isNetworkPrinter,roomId:common.roomId}});if(details?.kind==="network")await tx.insert(networkDetails).values({assetId:id,rackId:details.rackId,rackUnit:details.rackUnit,ipAddress:details.ipAddress,macAddress:details.macAddress,managementAddress:details.managementAddress,hostname:details.hostname,installationPoint:details.installationPoint,responsibleProfileId:details.responsibleProfileId}).onConflictDoUpdate({target:networkDetails.assetId,set:{rackId:details.rackId,rackUnit:details.rackUnit,ipAddress:details.ipAddress,macAddress:details.macAddress,managementAddress:details.managementAddress,hostname:details.hostname,installationPoint:details.installationPoint,responsibleProfileId:details.responsibleProfileId}});if(newCode)await tx.insert(assetMovements).values({assetId:id,type:"RACK_CHANGED",oldAssetCode:oldCode,newAssetCode:newCode,actorId:user.id,metadata:{}});await tx.insert(siteAuditLogs).values({actorId:user.id,action:"ASSET_UPDATED",entityType:"ASSET",entityId:id,metadata:{oldCode,newCode,status:common.status}});return asset}));return ok(updated)}catch(error){return errorResponse(error)}}
