import { and, asc, eq } from "drizzle-orm";
import { currentUser } from "@/src/auth/session";
import { requireAdmin } from "@/src/auth/access";
import { controlDb } from "@/src/db/control";
import { buildings, centralAuditLogs, floors, provinces, racks, rooms, siteConnections, sites } from "@/src/db/control-schema";
import { locationCreateSchema, locationUpdateSchema } from "@/src/validation/admin";
import { AppError, errorResponse, ok } from "@/src/lib/errors";
import { encryptSiteConnection } from "@/src/lib/secrets";
export async function GET(){try{await currentUser();const [provinceRows,siteRows,buildingRows,floorRows,roomRows,rackRows]=await Promise.all([controlDb.select().from(provinces).orderBy(asc(provinces.name)),controlDb.select().from(sites).orderBy(asc(sites.name)),controlDb.select().from(buildings).orderBy(asc(buildings.name)),controlDb.select().from(floors).orderBy(asc(floors.name)),controlDb.select().from(rooms).orderBy(asc(rooms.name)),controlDb.select().from(racks).orderBy(asc(racks.name))]);return ok({provinces:provinceRows,sites:siteRows,buildings:buildingRows,floors:floorRows,rooms:roomRows,racks:rackRows})}catch(error){return errorResponse(error)}}
export async function POST(request:Request){try{const user=await currentUser();requireAdmin(user);const parsed=locationCreateSchema.safeParse(await request.json());if(!parsed.success)throw new AppError("VALIDATION_ERROR","Lokasyon bilgileri geçersiz.",400,parsed.error.flatten());const data=parsed.data;let created:{id:string}|undefined;if(data.entity==="province"){[created]=await controlDb.insert(provinces).values({name:data.name,code:data.code.toUpperCase()}).returning({id:provinces.id})}else if(data.entity==="site"){[created]=await controlDb.insert(sites).values({provinceId:data.provinceId,name:data.name,code:data.code.toUpperCase()}).returning({id:sites.id});if(data.connectionUrl&&created)await controlDb.insert(siteConnections).values({siteId:created.id,encryptedUrl:encryptSiteConnection(data.connectionUrl)})}else if(data.entity==="building"){[created]=await controlDb.insert(buildings).values({siteId:data.siteId,name:data.name,code:data.code}).returning({id:buildings.id})}else if(data.entity==="floor"){[created]=await controlDb.insert(floors).values({buildingId:data.buildingId,name:data.name,code:data.code}).returning({id:floors.id})}else if(data.entity==="room"){[created]=await controlDb.insert(rooms).values({floorId:data.floorId,name:data.name,code:data.code}).returning({id:rooms.id})}else{const [validRoom]=await controlDb.select({id:rooms.id}).from(rooms).innerJoin(floors,eq(floors.id,rooms.floorId)).innerJoin(buildings,eq(buildings.id,floors.buildingId)).where(and(eq(rooms.id,data.roomId),eq(buildings.siteId,data.siteId))).limit(1);if(!validRoom)throw new AppError("VALIDATION_ERROR","Oda seçilen lokasyona ait değil.",400);[created]=await controlDb.insert(racks).values({siteId:data.siteId,roomId:data.roomId,number:data.number,name:data.name,shortCode:data.shortCode.toUpperCase(),description:data.description}).returning({id:racks.id})}if(!created)throw new Error("Kayıt oluşturulamadı");await controlDb.insert(centralAuditLogs).values({actorId:user.id,action:"LOCATION_CREATED",entityType:data.entity.toUpperCase(),entityId:created.id,metadata:{}});return ok(created,{status:201})}catch(error){return errorResponse(error)}}
export async function PATCH(request:Request){try{const user=await currentUser();requireAdmin(user);const parsed=locationUpdateSchema.safeParse(await request.json());if(!parsed.success)throw new AppError("VALIDATION_ERROR","Güncelleme bilgileri geçersiz.",400,parsed.error.flatten());const {entity,id,...changes}=parsed.data;let updated:{id:string}|undefined;if(entity==="province"){[updated]=await controlDb.update(provinces).set({name:changes.name,code:changes.code,isActive:changes.isActive}).where(eq(provinces.id,id)).returning({id:provinces.id})}else if(entity==="site"){[updated]=await controlDb.update(sites).set({name:changes.name,code:changes.code,isActive:changes.isActive}).where(eq(sites.id,id)).returning({id:sites.id})}else if(entity==="building"){[updated]=await controlDb.update(buildings).set({name:changes.name,code:changes.code,isActive:changes.isActive}).where(eq(buildings.id,id)).returning({id:buildings.id})}else if(entity==="floor"){[updated]=await controlDb.update(floors).set({name:changes.name,code:changes.code,isActive:changes.isActive}).where(eq(floors.id,id)).returning({id:floors.id})}else if(entity==="room"){[updated]=await controlDb.update(rooms).set({name:changes.name,code:changes.code,isActive:changes.isActive}).where(eq(rooms.id,id)).returning({id:rooms.id})}else{[updated]=await controlDb.update(racks).set({name:changes.name,number:changes.number,shortCode:changes.shortCode,description:changes.description,isActive:changes.isActive}).where(eq(racks.id,id)).returning({id:racks.id})}if(!updated)throw new AppError("NOT_FOUND","Kayıt bulunamadı.",404);await controlDb.insert(centralAuditLogs).values({actorId:user.id,action:"LOCATION_UPDATED",entityType:entity.toUpperCase(),entityId:id,metadata:changes});return ok(updated)}catch(error){return errorResponse(error)}}
