import { hash } from "bcryptjs";
import { asc, eq, inArray } from "drizzle-orm";
import { currentUser } from "@/src/auth/session";
import { requireAdmin } from "@/src/auth/access";
import { controlDb } from "@/src/db/control";
import { adProfiles, appUsers, centralAuditLogs, userScopes } from "@/src/db/control-schema";
import { createAppUserSchema } from "@/src/validation/users";
import { AppError, errorResponse, ok } from "@/src/lib/errors";
export async function GET(){try{const actor=await currentUser();requireAdmin(actor);const users=await controlDb.select({id:appUsers.id,adProfileId:appUsers.adProfileId,username:appUsers.username,displayName:appUsers.displayName,email:appUsers.email,role:appUsers.role,isActive:appUsers.isActive,createdAt:appUsers.createdAt}).from(appUsers).orderBy(asc(appUsers.displayName));const ids=users.map(u=>u.id);const scopes=ids.length?await controlDb.select().from(userScopes).where(inArray(userScopes.userId,ids)):[];return ok(users.map(user=>({...user,scopes:scopes.filter(scope=>scope.userId===user.id)})))}catch(error){return errorResponse(error)}}
export async function POST(request:Request){try{const actor=await currentUser();requireAdmin(actor);const parsed=createAppUserSchema.safeParse(await request.json());if(!parsed.success)throw new AppError("VALIDATION_ERROR","Kullanıcı ve kapsam bilgileri geçersiz.",400,parsed.error.flatten());const input=parsed.data;const [profile]=await controlDb.select().from(adProfiles).where(eq(adProfiles.id,input.adProfileId)).limit(1);if(!profile?.isActive)throw new AppError("NOT_FOUND","Aktif AD profili bulunamadı.",404);const created=await controlDb.transaction(async tx=>{const [user]=await tx.insert(appUsers).values({adProfileId:profile.id,username:profile.username,displayName:profile.displayName,email:profile.email,passwordHash:await hash(input.password,12),role:input.role}).returning();if(!user)throw new Error("Kullanıcı oluşturulamadı");await tx.insert(userScopes).values(input.scopes.map(scope=>({userId:user.id,type:scope.type,provinceId:scope.provinceId,siteId:scope.siteId})));await tx.insert(centralAuditLogs).values({actorId:actor.id,action:"APP_USER_CREATED",entityType:"APP_USER",entityId:user.id,metadata:{role:user.role,scopeCount:input.scopes.length}});return user});return ok(created,{status:201})}catch(error){return errorResponse(error)}}
