import { and, eq, or } from "drizzle-orm";
import { currentUser } from "@/src/auth/session";
import { authorizeSite, requireWriteRole } from "@/src/auth/access";
import { assetRelations, assets, siteAuditLogs } from "@/src/db/site-schema";
import { resolveSiteConnection } from "@/src/db/site-resolver";
import { withSiteDb } from "@/src/db/site-manager";
import { assetRelationSchema } from "@/src/validation/assets";
import { AppError, errorResponse, ok } from "@/src/lib/errors";
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){try{const user=await currentUser();const siteId=new URL(request.url).searchParams.get("siteId");if(!siteId)throw new AppError("VALIDATION_ERROR","siteId zorunludur.",400);await authorizeSite(user,siteId);const id=(await params).id;const url=await resolveSiteConnection(siteId);return ok(await withSiteDb(siteId,url,db=>db.select({id:assetRelations.id,type:assetRelations.type,sourceAssetId:assetRelations.sourceAssetId,targetAssetId:assetRelations.targetAssetId,sourceName:assets.name}).from(assetRelations).leftJoin(assets,or(eq(assets.id,assetRelations.sourceAssetId),eq(assets.id,assetRelations.targetAssetId))).where(or(eq(assetRelations.sourceAssetId,id),eq(assetRelations.targetAssetId,id)))))}catch(error){return errorResponse(error)}}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){try{const user=await currentUser();requireWriteRole(user);const parsed=assetRelationSchema.safeParse(await request.json());if(!parsed.success)throw new AppError("VALIDATION_ERROR","Bağlantı bilgileri geçersiz.",400,parsed.error.flatten());await authorizeSite(user,parsed.data.siteId);const sourceAssetId=(await params).id;if(sourceAssetId===parsed.data.targetAssetId)throw new AppError("VALIDATION_ERROR","Varlık kendisine bağlanamaz.",400);const url=await resolveSiteConnection(parsed.data.siteId);const relation=await withSiteDb(parsed.data.siteId,url,db=>db.transaction(async tx=>{const found=await tx.select({id:assets.id}).from(assets).where(and(eq(assets.siteId,parsed.data.siteId),or(eq(assets.id,sourceAssetId),eq(assets.id,parsed.data.targetAssetId))));if(found.length!==2)throw new AppError("NOT_FOUND","Bağlanacak varlıklardan biri bulunamadı.",404);const [created]=await tx.insert(assetRelations).values({sourceAssetId,targetAssetId:parsed.data.targetAssetId,type:parsed.data.type}).returning();if(!created)throw new Error("Bağlantı oluşturulamadı");await tx.insert(siteAuditLogs).values({actorId:user.id,action:"ASSET_RELATION_CREATED",entityType:"ASSET_RELATION",entityId:created.id,metadata:{sourceAssetId,targetAssetId:parsed.data.targetAssetId,type:parsed.data.type}});return created}));return ok(relation,{status:201})}catch(error){return errorResponse(error)}}
export async function DELETE(request:Request){try{const user=await currentUser();requireWriteRole(user);const urlObject=new URL(request.url);const siteId=urlObject.searchParams.get("siteId");const relationId=urlObject.searchParams.get("relationId");if(!siteId||!relationId)throw new AppError("VALIDATION_ERROR","siteId ve relationId zorunludur.",400);await authorizeSite(user,siteId);const url=await resolveSiteConnection(siteId);const removed=await withSiteDb(siteId,url,db=>db.delete(assetRelations).where(eq(assetRelations.id,relationId)).returning({id:assetRelations.id}));if(!removed[0])throw new AppError("NOT_FOUND","Bağlantı bulunamadı.",404);return ok(removed[0])}catch(error){return errorResponse(error)}}
