import { asc, eq } from "drizzle-orm";
import { z } from "zod";
import { currentUser } from "@/src/auth/session";
import { controlDb } from "@/src/db/control";
import { adOuMappings, centralAuditLogs, sites, unmatchedAdRecords } from "@/src/db/control-schema";
import { AppError, errorResponse, ok } from "@/src/lib/errors";
const resolveSchema=z.object({recordId:z.string().uuid(),siteId:z.string().uuid()});
export async function GET(){try{const user=await currentUser();if(user.role!=="ADMIN"&&user.role!=="IT_OPERATOR")throw new AppError("FORBIDDEN","AD eşleştirme kayıtlarını görme yetkiniz yok.",403);return ok(await controlDb.select().from(unmatchedAdRecords).where(eq(unmatchedAdRecords.isResolved,false)).orderBy(asc(unmatchedAdRecords.firstSeenAt)))}catch(error){return errorResponse(error)}}
export async function POST(request:Request){try{const user=await currentUser();if(user.role!=="ADMIN"&&user.role!=="IT_OPERATOR")throw new AppError("FORBIDDEN","AD eşleştirme yetkiniz yok.",403);const parsed=resolveSchema.safeParse(await request.json());if(!parsed.success)throw new AppError("VALIDATION_ERROR","Eşleştirme bilgileri geçersiz.",400,parsed.error.flatten());const [record]=await controlDb.select().from(unmatchedAdRecords).where(eq(unmatchedAdRecords.id,parsed.data.recordId)).limit(1);const [site]=await controlDb.select({id:sites.id}).from(sites).where(eq(sites.id,parsed.data.siteId)).limit(1);if(!record||!site)throw new AppError("NOT_FOUND","AD kaydı veya lokasyon bulunamadı.",404);const ouDn=record.distinguishedName.split(",").slice(1).join(",");if(!ouDn)throw new AppError("VALIDATION_ERROR","Kayıttan OU bilgisi çıkarılamadı.",400);await controlDb.transaction(async tx=>{await tx.insert(adOuMappings).values({ouDn,siteId:site.id}).onConflictDoUpdate({target:adOuMappings.ouDn,set:{siteId:site.id,isActive:true}});await tx.update(unmatchedAdRecords).set({isResolved:true,resolvedSiteId:site.id,lastSeenAt:new Date()}).where(eq(unmatchedAdRecords.id,record.id));await tx.insert(centralAuditLogs).values({actorId:user.id,action:"AD_OU_MAPPED",entityType:"AD_OU_MAPPING",entityId:record.id,siteId:site.id,metadata:{ouDn}})});return ok({recordId:record.id,siteId:site.id,ouDn})}catch(error){return errorResponse(error)}}
